[toolchain]
anchor_version = "0.31.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
jackpot = "4PhNzNQ7XZAPrFmwcBFMe2ZY8ZaQWos8nJjcsjv1CHyh"

[programs.devnet]
jackpot = "4PhNzNQ7XZAPrFmwcBFMe2ZY8ZaQWos8nJjcsjv1CHyh"

[programs.mainnet]
jackpot = "3wi11KBqF3Qa7JPP6CH4AFrcXbvaYEXMsEr9cmWQy8Zj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../keypar.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
