name = "roll2roll-rpc-proxy"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[vars]
ALLOWED_ORIGINS = "https://casino-rho-lime.vercel.app,https://roll2roll-hackathon.vercel.app,http://localhost:5173,http://localhost:5174"
